version: '3.9'
services:
  jenkins:
    restart: unless-stopped
    build: .
    ports:
      #8080:8080
      - 50000:5000
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - jenkins
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


volumes:
  jenkins: